version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./logs:/logs
